### ISSUE TITLE
Script no longer working, unexpected page when time slot is found

### ISSUE THREAD

**Issue by mrAaaaaa** [kalkih/passport-appointment-bot#10]
The booking system now has a reCaptcha that prevents the script from booking. Is there a solution for this?

**Comment by mrAaaaaa** [comment]
[19:32:29] [error]      Something went wrong when trying to book timeslot
[19:32:29] [error]      Unexpected page
[19:32:29] [error]      Error
    at BookingService.provideContactDetails (C:\snapshot\pass-bot\src\bookingService.js:287:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async BookingService.bookSlot (C:\snapshot\pass-bot\src\bookingService.js:165:7)
    at async handleBooking (C:\snapshot\pass-bot\src\index.js:124:19)
[19:32:29] [error]      Failed booking slot 2022-10-31 09:40:00

**Comment by xxandeer** [comment]
Can you past your .error.log

**Comment by mrAaaaaa** [comment]
Nevermind, just noticed my config file was not 100% correct, works fine.. Good to know that the reCaptcha has not stopped it :D Thanks!
