### ISSUE TITLE
Throttle if error code?

### ISSUE THREAD

**Issue by vacumet** [kalkih/passport-appointment-bot#2]
After running every minute this morning i got this message:

2022-03-23T08:20:35+01:00 Error: Post was not a redirect
    at file:///home/banana/pass/pass-bokning-main/src/main.mjs:33:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async pickTime (file:///home/banana/pass/pass-bokning-main/src/flow/5.pickTime.mjs:37:16)
    at async main (file:///home/banana/pass/pass-bokning-main/src/main.mjs:76:27)
    at async watchMain (file:///home/banana/pass/pass-bokning-main/src/entry.mjs:56:17)
    at async entry (file:///home/banana/pass/pass-bokning-main/src/entry.mjs:89:20) {
  statusCode: 418
}

I changed the IP for the request and changed to every 3 minutes. A throttle feature would be nice :)

**Comment by kalkih** [comment]
I've never seen this behaviour myself, although I've not ran the program for longer than ~30 minutes at a time.
Could there be some form of rate limiting on your network?

I'll add a throttle setting.

**Comment by kalkih** [comment]
Added, see the `throttle` configuration option.

This will add a timeout (in seconds configured) between the requests when searching for available times.
