### ISSUE TITLE
Reached maximum redirect of ${maxRedirect} for URL: ${requestUrl} [v3.3.0]

### ISSUE THREAD

**Issue by danwie** [kalkih/passport-appointment-bot#21]
For some reason it's crashing as soon as I start it.

I'm using

  "sessions": 6,
  "throttle": 0.25

But I have also tried with less sessions and more throttle. Makes no difference.

```
$ ./passport-appointment-bot-macos-x64 
[16:50:48] [info]	Validating configuration...
[16:50:48] [success]	Configuration is valid
[16:50:48] [info]	Validating configured region...
[16:50:48] [success]	Valid region Stockholm
[16:50:48] [info]	Validating configured locations...
[16:50:48] [success]	Valid locations Flemingsberg, Globen, Haninge, Järva, Nacka, Norrtälje, Sollentuna, Solna, Sthlm City, Södertälje
[16:50:48] [info]	Starting booking session...
[16:50:48] [verbose]	Started captcha webserver on port 57132
/snapshot/pass-bot/node_modules/fetch-cookie/cjs/index.js:145
      throw new TypeError(`Reached maximum redirect of ${maxRedirect} for URL: ${requestUrl}`);
            ^

TypeError: Reached maximum redirect of 20 for URL: https://bokapass.nemoq.se/Booking/403.htm
    at /snapshot/pass-bot/node_modules/fetch-cookie/cjs/index.js:145:13
    at Generator.next (<anonymous>)
    at /snapshot/pass-bot/node_modules/fetch-cookie/cjs/index.js:62:61
    at new Promise (<anonymous>)
    at __async (/snapshot/pass-bot/node_modules/fetch-cookie/cjs/index.js:46:10)
    at handleRedirect (/snapshot/pass-bot/node_modules/fetch-cookie/cjs/index.js:124:10)
    at /snapshot/pass-bot/node_modules/fetch-cookie/cjs/index.js:227:20
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/pass-bot/node_modules/fetch-cookie/cjs/index.js:49:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Comment by danwie** [comment]
Issue was solved by waiting 5 minutes, then start application again.

**Comment by geekteq** [comment]
> Issue was solved by waiting 5 minutes, then start application again.
> Edit: Same problem started again. I think my settings are ok.

You are being blocked by IP used for too many requests. I get the same thing after a while and switching IP (I use VPN) resolves it so I assume you have the same issue. Probably times out in a while. Takes longer for me than 5 minutes but most likely because I run 1, 0.25 instead of 6, 0.25 :)

**Comment by danwie** [comment]
Thanks. VPN solved it for me as well.
