### ISSUE TITLE
NPM not being able to find package.json

### ISSUE THREAD

**Issue by jappish84** [kalkih/passport-appointment-bot#8]
This is probably a user error, but I can't seem to figure out what I'm doing wrong. 

I can see in the logs that  `package.json`  is missing, so I even tried copying the contents of the file from source bu ended up with the last code block below. 

Super thankful if you could point me in the right direction

```
osmc@Vardagsrum:~/passbot$ npm start passport-appointment-bot
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/osmc/passbot/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/osmc/passbot/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent


npm ERR! A complete log of this run can be found in:
npm ERR!     /home/osmc/.npm/_logs/2022-03-30T19_33_35_633Z-debug.log

```

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'start',
1 verbose cli   'passport-appointment-bot'
1 verbose cli ]
2 info using npm@6.14.16
3 info using node@v14.19.1
4 verbose stack Error: ENOENT: no such file or directory, open '/home/osmc/passbot/package.json'
5 verbose cwd /home/osmc/passbot
6 verbose Linux 4.14.78-4-osmc
7 verbose argv "/usr/bin/node" "/usr/bin/npm" "start" "passport-appointment-bot"
8 verbose node v14.19.1
9 verbose npm  v6.14.16
10 error code ENOENT
11 error syscall open
12 error path /home/osmc/passbot/package.json
13 error errno -2
14 error enoent ENOENT: no such file or directory, open '/home/osmc/passbot/package.json'
15 error enoent This is related to npm not being able to find a file.
16 verbose exit [ -2, true ]
```

```
osmc@Vardagsrum:~/passbot$ nano package.json
osmc@Vardagsrum:~/passbot$ npm start /home/osmc/passbot/passport-appointment-bot

> passport-appointment-bot@2.2.1 start /home/osmc/passbot
> node ./src/index "/home/osmc/passbot/passport-appointment-bot"

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/home/osmc/passbot/src/index'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! passport-appointment-bot@2.2.1 start: `node ./src/index "/home/osmc/passbot/passport-appointment-bot"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the passport-appointment-bot@2.2.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/osmc/.npm/_logs/2022-03-30T19_39_17_785Z-debug.log
```

**Comment by kalkih** [comment]
Ensure you are located in the the root directory of the source files, (you should have `package.json` & `config.json` here e.t.c.).


Before you begin, edit `config.json` with your information if you've not done so already.

* Run `npm install`, this will download all the dependencies of the application, wait for it to finish.
* Run `npm start`, this will run the applciation.

If you still have issues I would recommend starting over from a clean slate, delete all files, clone the source again, then run the two steps listed above.


Another alternative would be to download the precompiled executable for your OS (as well as config.json) from the latest release.

Then run it with `./name-of-the-file` when you are located in the same directory as the downloaded files.
If this fails, you might have to make the file executable first, if so run `sudo chmod +x name-of-the-file`.
https://github.com/kalkih/passport-appointment-bot/releases/latest

**Comment by jappish84** [comment]
I'm sorry, I'm an idiot, I just assumed that my machine was arm64, it wasn't. Works great after changing to the appropriate executable.

Big thanks for an awesome tool 👍
